disable persistance of intervals... if in scale mode, BedTools chokes
pyBedTools throws:
pybedtools.cbedtools.MalformedBedLineError: Unable to detect format from
['chr1\t3071063\t3081063\tL1Md_T\t5858\t+\n',
'chr1\t3081063\t3081766\tL1Md_T\t5858\t+\n',
'chr1\t3081766\t3091766\tL1Md_T\t5858\t+\n']

because these intervals are really a three-tuple!